Repository moeru-ai/xsai, pull requests merged in 2025-02, with the labels that each got.

#39 fix(utils-chat): array tool calls incorrectly constructed
  packages/utils-chat/src/message.ts
Labels: bug

#42 feat(xsfetch): basic implement
  cspell.config.yaml
  packages/xsfetch/src/index.ts
Labels: enhancement

#43 refactor(tool)!: use common tool type
  docs/content/docs/get-started/tool.mdx
  packages/generate-text/src/index.ts
  packages/shared-chat/src/types/tool.ts
  packages/tool/package.json
  packages/tool/src/generate-text.ts
  packages/tool/src/index.ts
  packages/xsai/src/index.ts
  pnpm-lock.yaml
Labels: bug, enhancement

#45 feat(providers): add openrouter
  cspell.config.yaml
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/openrouter.ts
  packages/providers/src/types/provider.ts
Labels: enhancement

#46 feat(providers): add deepseek
  cspell.config.yaml
  packages/providers/src/providers/deepseek.ts
  packages/providers/src/providers/index.ts
Labels: enhancement

#47 docs: fix missing link
  docs/content/docs/get-started/overview.mdx
Labels: documentation

#48 feat(providers): add silicon-flow
  cspell.config.yaml
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/silicon-flow.ts
Labels: enhancement

#49 feat(providers): added novita
  cspell.config.yaml
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/novita.ts
Labels: enhancement

#50 chore(eslint): ignore cspell config
  cspell.config.yaml
  eslint.config.ts
Labels: enhancement

#51 feat(providers): add workers-ai
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/workers-ai.ts
Labels: enhancement

#54 feat(providers): add groq
  cspell.config.yaml
  packages/providers/src/providers/groq.ts
  packages/providers/src/providers/index.ts
Labels: enhancement

#52 feat(providers): add together-ai
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/together-ai.ts
Labels: enhancement

#55 feat(providers): add fireworks-ai
  cspell.config.yaml
  packages/providers/src/providers/fireworks-ai.ts
  packages/providers/src/providers/index.ts
Labels: enhancement

#56 feat(providers): add perplexity
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/perplexity.ts
Labels: enhancement

#57 feat(providers): add mistral-ai
  cspell.config.yaml
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/mistral-ai.ts
Labels: enhancement

#58 feat(providers): add qwen
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/qwen.ts
Labels: enhancement

#59 feat(providers): add xai
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/xai.ts
Labels: enhancement

#60 feat(providers): add tencent-hunyuan
  cspell.config.yaml
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/tencent-hunyuan.ts
Labels: enhancement

#61 feat(providers): add moonshot
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/moonshot.ts
Labels: enhancement

#62 feat(providers): add minimax
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/minimax.ts
Labels: enhancement

#63 feat(providers): add stepfun
  cspell.config.yaml
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/stepfun.ts
Labels: enhancement

#64 feat(providers): add zhipu
  cspell.config.yaml
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/zhipu.ts
Labels: enhancement

#68 fix(providers): incorrect baseUrl for qwen
  packages/providers/src/providers/qwen.ts
Labels: bug

#70 refactor: use publish config with tsup
  .gitignore
  cspell.config.yaml
  docs/content/docs/get-started/embed.mdx
  docs/content/docs/get-started/generate/object.mdx
  docs/content/docs/get-started/generate/speech.mdx
  docs/content/docs/get-started/generate/text.mdx
  docs/content/docs/get-started/generate/transcription.mdx
  docs/content/docs/get-started/model.mdx
  docs/content/docs/get-started/providers.mdx
  docs/content/docs/get-started/stream-text.mdx
  docs/content/docs/get-started/tool.mdx
  docs/content/docs/references/embed.model.mdx
  docs/content/docs/references/generate-object.model.mdx
  docs/content/docs/references/generate-speech.model.mdx
  docs/content/docs/references/generate-text.model.mdx
  docs/content/docs/references/generate-transcription.model.mdx
  docs/content/docs/references/providers.model.mdx
  docs/content/docs/references/shared-chat.model.mdx
  docs/content/docs/references/stream-object.model.mdx
  docs/content/docs/references/stream-text.model.mdx
  docs/content/docs/references/tool.model.mdx
  docs/content/docs/references/xsai.model.mdx
  docs/generate-files.ts
  docs/lib/references/embed.ts
  docs/lib/references/generate-object.ts
  docs/lib/references/generate-speech.ts
  docs/lib/references/generate-text.ts
  docs/lib/references/generate-transcription.ts
  docs/lib/references/providers.ts
  docs/lib/references/shared-chat.ts
  docs/lib/references/stream-object.ts
  docs/lib/references/stream-text.ts
  docs/lib/references/tool.ts
  docs/lib/references/xsai.ts
  docs/package.json
  package.json
  packages/embed/package.json
  packages/generate-object/package.json
  packages/generate-speech/package.json
  packages/generate-text/package.json
  packages/generate-transcription/package.json
  packages/model/package.json
  packages/providers/package.json
  packages/providers/tsup.config.ts
  packages/shared-chat/package.json
  packages/shared/package.json
  packages/stream-object/package.json
  packages/stream-text/package.json
  packages/tool/package.json
  packages/utils-chat/package.json
  packages/utils-stream/package.json
  packages/xsai/package.json
  packages/xsai/tsup.config.ts
  packages/xsfetch/package.json
  packages/xsschema/package.json
  pnpm-lock.yaml
  tsconfig.node.json
  tsup.config.ts
Labels: enhancement

#73 feat(providers-cloud): add deepinfra
  cspell.config.yaml
  packages-ext/providers-cloud/src/providers/deepinfra.ts
  packages-ext/providers-cloud/src/providers/index.ts
Labels: enhancement

#75 feat(providers-cloud): added cerebras
  cspell.config.yaml
  packages-ext/providers-cloud/src/providers/cerebras.ts
  packages-ext/providers-cloud/src/providers/index.ts
Labels: enhancement

#78 feat(xsschema): support arktype
  cspell.config.yaml
  packages/xsschema/package.json
  packages/xsschema/src/to-json-schema/arktype.ts
  packages/xsschema/src/to-json-schema/index.ts
  packages/xsschema/test/__snapshots__/to-json-schema.test.ts.snap
  packages/xsschema/test/to-json-schema.test.ts
  pnpm-lock.yaml
Labels: enhancement

#76 docs: update
  docs/app/global.css
  docs/components.json
  docs/components/pkg-size-chart.tsx
  docs/components/ui/card.tsx
  docs/components/ui/chart.tsx
  docs/content/docs/index.mdx
  docs/lib/utils.ts
  docs/package.json
  docs/source.config.ts
  eslint.config.ts
  pnpm-lock.yaml
Labels: documentation

#82 feat(embed,shared-provider): export response, extend more provider generics
  packages-ext/shared-providers/src/types/providers.ts
  packages-ext/shared-providers/src/utils/create.ts
  packages/embed/src/index.ts
Labels: enhancement
