Repository moeru-ai/xsai, pull requests merged in 2025-01, with the labels that each got.

#14 feat(providers): add unspeech, unelevenlabs
  cspell.config.yaml
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/openai.ts
  packages/providers/src/providers/unspeech/elevenlabs.ts
  packages/providers/src/providers/unspeech/index.ts
  packages/providers/src/types/provider.ts
Labels: enhancement

#17 feat: improve error handling
  packages/embed/src/utils/embed-many.ts
  packages/embed/src/utils/embed.ts
  packages/generate-speech/src/index.ts
  packages/generate-text/src/index.ts
  packages/generate-transcription/src/index.ts
  packages/model/src/utils/list-models.ts
  packages/model/src/utils/retrieve-model.ts
  packages/shared-chat/src/error/index.ts
  packages/shared-chat/src/index.ts
  packages/shared-chat/src/utils/chat.ts
  packages/shared/src/error/index.ts
  packages/shared/src/index.ts
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/response-catch.ts
  packages/shared/src/utils/response-json.ts
  packages/stream-text/src/index.ts
Labels: enhancement

#19 refactor(providers)!: improve structure
  packages/providers/src/providers/index.ts
  packages/providers/src/providers/openai-compatible.ts
  packages/providers/src/providers/openai.ts
  packages/providers/src/providers/unspeech/elevenlabs.ts
  packages/providers/src/providers/unspeech/index.ts
  packages/providers/src/types/provider.ts
Labels: enhancement

#21 chore(providers/google-generative-ai): update model list
  packages/providers/src/providers/google-generative-ai.ts
Labels: documentation

#22 feat(generate-text): add toolCalls
  packages/generate-object/src/index.ts
  packages/generate-text/src/index.ts
Labels: enhancement

#25 refactor(generate-text): trampoline function
  packages/generate-text/src/index.ts
  packages/generate-text/test/__snapshots__/index.test.ts.snap
  packages/generate-text/test/index.test.ts
  packages/tool/test/index.test.ts
Labels: enhancement

#26 feat(generate-text): add onStepFinish()
  packages/generate-text/src/index.ts
  packages/generate-text/test/index.test.ts
Labels: enhancement

#27 feat(stream-text): add onChunk()
  packages/stream-text/src/index.ts
  packages/stream-text/test/__snapshots__/index.test.ts.snap
  packages/stream-text/test/index.test.ts
Labels: enhancement

#31 fix(stream-text): incorrectly handled errors
  packages/stream-text/src/index.ts
Labels: bug

#35 feat(tool): add execute options
  packages/generate-text/src/index.ts
  packages/shared-chat/src/types/tool.ts
  packages/tool/src/generate-text.ts
Labels: enhancement

#37 feat(generate-text): return messages
  packages/generate-object/src/index.ts
  packages/generate-text/src/index.ts
Labels: enhancement
