Repository moeru-ai/xsai, pull requests merged in 2025-03, with the labels that each got.

#86 feat(provider-local): added microsoft
  cspell.config.yaml
  packages-ext/providers-local/src/providers/index.ts
  packages-ext/providers-local/src/providers/unspeech/microsoft.ts
Labels: enhancement

#88 fix(xsfetch): make `retry` work, remove the exposure of `retryCount`
  packages/xsfetch/src/index.ts
Labels: bug

#84 feat: new package `@xsai-ext/mcp`
  cspell.config.yaml
  docs/content/docs/references/meta.json
  packages-ext/mcp/package.json
  packages-ext/mcp/src/index.ts
  packages-ext/mcp/src/sse.ts
  packages-ext/mcp/src/stdio.ts
  packages-ext/mcp/src/utils/map-tools.ts
  packages-ext/mcp/tsup.config.ts
  pnpm-lock.yaml
  tsconfig.lib.json
Labels: enhancement

#92 docs: add integrations, remove package `@xsai-ext/mcp`
  cspell.config.yaml
  docs/app/layout.config.tsx
  docs/content/docs/integrations/tools/agentic.mdx
  docs/content/docs/integrations/tools/composio.mdx
  docs/content/docs/integrations/tools/model-context-protocol.mdx
  docs/content/docs/meta.json
  docs/content/docs/references/meta.json
  packages-ext/mcp/package.json
  packages-ext/mcp/src/index.ts
  packages-ext/mcp/src/sse.ts
  packages-ext/mcp/src/stdio.ts
  packages-ext/mcp/src/utils/get-tools.ts
  packages-ext/mcp/tsup.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.lib.json
Labels: documentation

#93 docs: add utils
  docs/content/docs/packages/meta.json
  docs/content/docs/packages/utils/chat.mdx
  docs/content/docs/packages/utils/stream.mdx
  docs/package.json
  packages/utils-stream/src/simulate-readable-stream.ts
  packages/utils-stream/src/to-async-iterator.ts
  pnpm-lock.yaml
Labels: documentation

#95 feat(tool): support multimodal & object result
  packages/generate-text/src/index.ts
  packages/shared-chat/src/types/message.ts
  packages/shared-chat/src/types/tool.ts
  packages/shared-chat/src/utils/index.ts
  packages/shared-chat/src/utils/wrap-tool-result.ts
  packages/stream-text/src/index.ts
  packages/tool/src/index.ts
Labels: bug, enhancement

#94 feat: new package `@xsai-ext/compat`
  cspell.config.yaml
  docs/content/docs/meta.json
  docs/content/docs/packages-ext/compat.mdx
  docs/content/docs/references/meta.json
  docs/scripts/update-references.ts
  packages-ext/compat/package.json
  packages-ext/compat/src/index.ts
  packages-ext/compat/src/types/_unsupported.ts
  packages-ext/compat/src/types/index.ts
  packages-ext/compat/src/types/internal/messages-or-prompts.ts
  packages-ext/compat/src/types/model.ts
  packages-ext/compat/src/types/shared-chat.ts
  packages-ext/compat/src/utils/_unsupported.ts
  packages-ext/compat/src/utils/embed.ts
  packages-ext/compat/src/utils/generate-object.ts
  packages-ext/compat/src/utils/generate-text.ts
  packages-ext/compat/src/utils/index.ts
  packages-ext/compat/src/utils/internal/convert-prompts.ts
  packages-ext/compat/src/utils/internal/convert-tools.ts
  packages-ext/compat/src/utils/stream-object.ts
  packages-ext/compat/src/utils/stream-text.ts
  packages-ext/compat/src/utils/tool.ts
  packages/utils-stream/src/index.ts
  packages/xsai/package.json
  packages/xsai/src/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.lib.json
Labels: enhancement

#97 fix(providers-cloud/openrouter): add model provider
  packages-ext/providers-cloud/src/providers/openrouter.ts
Labels: bug

#99 docs: update contributing
  CONTRIBUTING.md
Labels: documentation

#103 docs(contributing): add missing embed model setup
  CONTRIBUTING.md
Labels: documentation

#106 feat(stream-text): return stepType, finishReason
  packages/generate-text/src/index.ts
  packages/generate-text/test/__snapshots__/index.test.ts.snap
  packages/shared-chat/src/types/index.ts
  packages/shared-chat/src/types/step-type.ts
  packages/shared-chat/src/utils/determine-step-type.ts
  packages/shared-chat/src/utils/execute-tool.ts
  packages/shared-chat/src/utils/index.ts
  packages/shared-chat/src/utils/internal/wrap-tool-result.ts
  packages/stream-text/src/index.ts
Labels: enhancement

#107 fix(providers-local): missing speed for elevenlabs, mark some fields non-optional, and fix object
  packages-ext/providers-local/src/providers/unspeech/elevenlabs.ts
Labels: bug

#108 fix(providers-local): export elevenlabs & microsoft from unspeech
  packages-ext/providers-local/src/providers/index.ts
Labels: bug

#109 fix(providers-local): to snake
  packages-ext/providers-local/src/providers/unspeech/elevenlabs.ts
Labels: bug

#115 feat(xsschema): support effect schema
  docs/content/docs/packages-top/xsschema.mdx
  docs/package.json
  packages-top/xsschema/package.json
  packages-top/xsschema/src/to-json-schema/effect.ts
  packages-top/xsschema/src/to-json-schema/index.ts
  packages-top/xsschema/test/__snapshots__/to-json-schema.test.ts.snap
  packages-top/xsschema/test/to-json-schema.test.ts
  packages/generate-object/package.json
  packages/generate-text/package.json
  packages/stream-object/package.json
  packages/stream-text/package.json
  packages/tool/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#118 feat(tool): returns schema
  docs/content/docs/packages/tool.mdx
  packages-ext/compat/src/utils/internal/convert-tools.ts
  packages-ext/compat/src/utils/tool.ts
  packages/shared-chat/src/types/tool.ts
  packages/shared-chat/src/utils/chat.ts
  packages/tool/src/index.ts
  packages/tool/test/index.test.ts
Labels: enhancement
